### ISSUE TITLE
How to download?

### ISSUE THREAD

**Issue by tyblakesley** [rrskybox/SuperScan#1]
I could not find the setup file to install this on my Windows 10 machine. I use TheSkyX and would love this Supernova search program.

**Comment by rrskybox** [comment]
My apologies.  I just picked up your question -- something is not working here with notifications, I guess.  Anyway, if you're still interested, I added the "Publish" directory to the repository.  Setup.exe is there.

**Comment by tyblakesley** [comment]
Thank you for getting back with me! I am new to github, made an account just to download this awesome search program. I downloaded the updated version and found the setup.exe file. It doesnt appear to install correctly on my machine. Say's application validation did not succeed and the following in the log file:

ERROR DETAILS
	Following errors were detected during this operation.
	* [2/10/2020 10:33:59 PM] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- Application manifest has either a different computed hash than the one specified or no hash specified at all. 
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- File, SuperScan.exe.manifest, has a different computed hash than specified in manifest.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)

**Comment by rrskybox** [comment]
I'm pretty sure that the problem is that you need to download the whole "Publish" directory contents to install the program.  I created a zip file in the Publish directory that has its contents in order to make the process easier:

1. Select the zip file
2. Download it.
3. Open it.
4. Run setup.exe
5. If prompted, with the scary "Windows protected your PC", then select "More Info" and "Run anyway".
6. If you ever get an error that says "cannot install because installed from another location", then just uninstall the SuperScan app and try again.

Let me know how this works for you and we'll go from there...

- Rick

**Comment by tyblakesley** [comment]
Hello Rick,

Got it to work, thank you! Will be playing with the software now, thanks
for all your help and the awesome program!

-Tony Blakesley
